[gcp_service_account]
type = "service_account"
project_id = "enjoi-442817"
private_key_id = "712e4fb1b597f5f7962ab5d0e7804ae17128ad11"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC9nsbuRmnEk10v
WzIYsCZtcxwb+fwFxKbE8/zFag8PBWTw3VKjIWem5ec5J49dNuABNt1T1CONbH+5
akVEtj3hAZTSgLxSjAISIeeaM6dx0Yd5Hm6HWM5XxUyXKCBz7qI4ntjzBRtXBigk
VHii2pJiRh2e11bxc4Ndn4NJqXthkquSMjAu69w+imfpWgbEGOJvgLzivmK5Iw1+
PO+cU2c8L1f2/xeMK5q5xJh7KFXWhW6TVaAea3xurrBZ8Yk67JUy+M2yuu7VCaWM
9OXObrzqowRFgswxTDYeanEONzy8cfzS2gzrmu0SB63aSVx54lg2WLG4v4HFBdS4
ttPKdzrvAgMBAAECggEACVFmnCnoo6jMMPoNxanOUZ2Q+Yz4xf3KZi5JMxhJoibV
NYLivzJyigCNMsFPabi7HEQqbyajEp2Mzzs6KSy9cLOnsQpzdqj7pxF0dJ7qMQ0n
V5vXuZ3zEdwXreviYGAPJ7IinhqXo9ihG1vtS69q9xpT9UzGsHnJME4Y4QNLlVlO
jZioimKxkuKa4e14H/RODMRoH7E7WXFK13r6a9kRuXdERbPwmHsX56XHBHv9mtOn
qdG3ULBe+/f0YzKShAiLDDFe/54uPHXW3rU2QtSM9Cjq0ckHm4q03kdp5+2YtXFi
EzUGw2KC3vWK+kBT+WOe9DlWtB7H8jHJRwInZwuGsQKBgQDuUBkbg0jK/HrHxX13
b1sLV4Uj3CmwVWlXqAAa5g/71Az4gOXZKX7vggt8ptTzVKsrVQg+7CE9bU6KY2EN
CPllUiCDHXS6AFTq9KWoxXfy+GKxIhIZ3+J50QV6cwuuGJ9g+AD5ItO4jsdOYr5z
bvOJo7exEfnG/6FjN1K+GgYtvwKBgQDLsYb3QWEDiiUbRMhTSCXagYzL2igwSf+4
FKb1ednjyvEmMM44bhD+yHYVukCJ1HZsTWpDjc8PuJtNBVAo/+fklPALOtbZ9jSQ
QyscwicYvqHcj9+NMV5nFiWeYFvoqmrbYpDuWokD3riFi6QWn7bTboWb2iFeXXQ
eTV4cNCe0QKBgQDPI4fvRhmLdhEyexInMf8syJHNLZx+zH6X1krhFn9mIFZ12XPv
YgYXIC3j1w7ZwgpVy78zEgOCZPQTjXXZ4qcDznK8BGplEcy9vJARNjKgWg1OcZLS
Mqujvm7IlB7e4EAIBQizg/YLQO8zzthDdXjxdgBARKOauK8Kkhe1bOFZ+QKBgC58
xK23aRmytIdFqmZ/Z8w3lteLYXKr4MW1SOlrNtQrI+AwcVAlppFPVMvepw4NxD0x
adgjDCetXRw14zaIOPdNGn+lnRU/gH2QJs24bc3S7AP3e99v0cXQbdNhxa2htRFf
vZd5QIUcV1Iz98qQLLWGRrsKEBOuRboff5mOPb6RAoGBAJgf6RpfXEJvmT52gk2/
C5yUYwzUsmj6uGBvXKUupEz7xjXznC+QilAytYdalDMuZPn1Ipwd19hDfPi5Rwel
4ipFNMw+U4FqZ1vNNV1KlDeq6AZexI4oz98MJzoPliUa9RfCiy3KJSMj6BIaZiwt
gbeROrvDSkAHsQlLPL/8MmIv
-----END PRIVATE KEY-----
"""
client_email = "enjoi-147@enjoi-442817.iam.gserviceaccount.com"
client_id = "113683969268463456672"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/v1/metadata/x509/enjoi-147@enjoi-442817.iam.gserviceaccount.com"

[sheets]
sheet_key = "1mD3lBTdf08W9qT3RriUBEZIOtQVTMCfhdU7P8YfCCy4"

[openphone]
api_key = "ebScqkTyM2AxT25gryN9F5qnyTT77vuz"
